let personsData = [
    {
        name: 'Кристиночка',
        sex: 'female',
        online: true,
        photos: 12,
        age: 28,
        top: true,
        registrationDate: '2017-09-03',
        city: 'Санкт-Петербург',
        country: 'Россия',
        img: 'img/lg-photo1.png'
    },
    {
        name: 'Диана',
        sex: 'female',
        online: true,
        photos: 3,
        age: 20,
        top: true,
        registrationDate: '2017-09-07',
        city: 'Самара',
        country: 'Россия',
        img: 'img/lg-photo2.png'
    },
    {
        name: 'Аня',
        sex: 'female',
        online: true,
        photos: 125,
        age: 18,
        top: true,
        registrationDate: '2017-09-02',
        city: 'Ростов-на-Дону',
        country: 'Россия',
        img: 'img/lg-photo3.png'
    },
    {
        name: 'Анжелика',
        sex: 'female',
        online: false,
        photos: 17,
        age: 27,
        top: false,
        registrationDate: '2015-03-04',
        city: ' Чебоксары',
        country: 'Россия',
        img: 'img/lg-photo4.png'
    },
    {
        name: 'Лариса',
        sex: 'female',
        online: true,
        photos: 12,
        age: 32,
        top: false,
        registrationDate: '2015-03-05',
        city: 'Москва',
        country: 'Россия',
        img: 'img/lg-photo5.png'
    },
    {
        name: 'Настя',
        sex: 'female',
        online: true,
        photos: 3,
        age: 21,
        top: false,
        registrationDate: '2015-03-06',
        city: 'Зеленоград',
        country: 'Россия',
        img: 'img/lg-photo6.png'
    },
    {
        name: 'Евгения',
        sex: 'female',
        online: false,
        photos: 4,
        age: 30,
        top: false,
        registrationDate: '2015-03-07',
        city: 'Ростов-на-Дону',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ольга',
        sex: 'female',
        online: true,
        photos: 28,
        age: 25,
        top: false,
        registrationDate: '2015-03-08',
        city: 'Казань',
        country: 'Россия',
        img: 'img/lg-photo8.png'
    },
    {
        name: 'Кристиночка',
        sex: 'female',
        online: false,
        photos: 12,
        age: 28,
        top: false,
        registrationDate: '2015-03-09',
        city: 'Санкт-Петербург',
        country: 'Россия',
        img: 'img/lg-photo2.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    {
        name: 'Ангелина',
        sex: 'female',
        online: false,
        photos: 20,
        age: 20,
        top: true,
        registrationDate: '2015-03-09',
        city: 'Воронеж',
        country: 'Россия',
        img: 'img/lg-photo7.png'
    },
    
];